### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scurl#44]
Hey @nctl144 I checked packaging by running ``python setup.py sdist`` and then installing ``dist/scurl-0.1.0.tar.gz`` in a fresh virtual environment (python3.6 on OS X), and everything worked well besides one issue: ``six`` is needed for ``scurl`` to work, but it's not listed in ``scurl`` requirements (https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires).

**Comment by nctl144** [comment]
yep I have added it to the requirements in setup.py, @lopuhin . Thank you for pointing that out 😄
